### ISSUE TITLE
Release 1.4.10 does not work with RoundCube 1.4.X

### ISSUE THREAD

**Issue by trollkotze** [gianlucagiacometti/roundcube-postfixadmin-toolbox#13]
I have RoundCube 1.4.11 installed.
I tried to install Toolbox plugin 1.4.10 (or 1.4.10.1 or 1.4.10.2) by unpacking the release tar-ball into the RoundCube plugins directory.
The menu items for the Toolbox plugin appear in RoundCube, but when clicking on anyhing, the interface is empty.
I checked the RoundCube error log, and I find this:
```[20-Mar-2021 08:17:43 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'rcmail_action' not found in /var/www/html/webmail/plugins/toolbox/toolbox.php:1204
Stack trace:
#0 /var/www/html/webmail/program/include/rcmail_output_html.php(1359): toolbox->tool_render_form(Array)
#1 [internal function]: rcmail_output_html->xml_command(Array)
#2 /var/www/html/webmail/program/include/rcmail_output_html.php(1209): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')
#3 /var/www/html/webmail/program/include/rcmail_output_html.php(781): rcmail_output_html->parse_xml('<roundcube:incl...')
#4 /var/www/html/webmail/program/include/rcmail_output_html.php(615): rcmail_output_html->parse('tooledit', false)
#5 /var/www/html/webmail/plugins/toolbox/toolbox.php(530): rcmail_output_html->send('toolbox.tooledi...')
#6 /var/www/html/webmail/program/lib/Roundcube/rcube_plugin_api.php(522): toolbox->init_html()
#7 /var/www/html/webmail/index.php(292): rcube_plugin_api->exec_action('plugin.toolbox....')
#8 {main}
  thrown in /var/www/html/webmail/plugins/toolbox/toolbox.php on line 1204```
  
  Apparently, the file `program/include/rcmail_action.php` is missing in RoundCube 1.4.X. It is present in the GitHub master, and 1.5 Beta.
  Is it really correct that this plugin is supposed to be working with RoundCube 1.4.X, as described?

**Comment by trollkotze** [comment]
Sorry, my mistake. I had installed 1.4.10.1, which only works with the GitHub version apparently.
